<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<REMITTable2 xmlns="http://www.acer.europa.eu/REMIT/REMITTable2_V1.xsd">
    <reportingEntityID>
        <ace>B0001064H.DE</ace>
    </reportingEntityID>
    <TradeList>
        <nonStandardContractReport>
            <RecordSeqNumber>1</RecordSeqNumber>
            <idOfMarketParticipant>
                <ace>A00023777.DE</ace>
            </idOfMarketParticipant>
            <otherMarketParticipant>
                <ace>A00113777.DE</ace>
            </otherMarketParticipant>
            <tradingCapacity>P</tradingCapacity>
            <buySellIndicator>S</buySellIndicator>
            <contractId>AQN1qaRf20kwi0GbI3tJlkwqp2z0OlFqVEWUCHTEST001</contractId>
            <contractDate>2021-11-29</contractDate>
            <contractType>FW</contractType>
            <energyCommodity>EL</energyCommodity>
            <priceOrPriceFormula>
                <priceFormula>0,51*DEBY+0,22*DEPY</priceFormula>
            </priceOrPriceFormula>
            <estimatedNotionalAmount>
                <value>0</value>
                <currency>EUR</currency>
            </estimatedNotionalAmount>
            <totalNotionalContractQuantity>
                <value>0</value>
                <unit>MWh</unit>
            </totalNotionalContractQuantity>
            <volumeOptionality>V</volumeOptionality>
            <typeOfIndexPrice>I</typeOfIndexPrice>
            <fixingIndexDetails>
                <fixingIndex>EEX DE Settlement</fixingIndex>
                <fixingIndexType>FU</fixingIndexType>
                <fixingIndexSource>EEX</fixingIndexSource>
                <firstFixingDate>2021-11-29</firstFixingDate>
                <lastFixingDate>2022-12-15</lastFixingDate>
                <fixingFrequency>O</fixingFrequency>
            </fixingIndexDetails>
            <settlementMethod>P</settlementMethod>
            <deliveryPointOrZone>10YDE-VE-------2</deliveryPointOrZone>
            <deliveryStartDate>2022-01-01</deliveryStartDate>
            <deliveryEndDate>2023-12-31</deliveryEndDate>
            <loadType>SH</loadType>
            <actionType>N</actionType>
        </nonStandardContractReport>
    </TradeList>
</REMITTable2>